import { Profile } from '../model/profile';
import { set } from 'date-fns';

const startDate = set(new Date(), { hours: 8, minutes: 30 });

const profiles = [
    new Profile({
        id: 1,
        username: 'johndoe',
        bio: 'I love to program and to type fast.',
        avgWPM: 122.34,
        highestWPM: 140.34,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 2,
        username: 'janedoe',
        bio: 'I enjoy solving puzzles and achieving high typing speeds.',
        avgWPM: 98,
        highestWPM: 120.34,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 3,
        username: 'michaelking',
        bio: 'Competitive typist and coder.',
        avgWPM: 115.2,
        highestWPM: 130.5,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 4,
        username: 'lindawalker',
        bio: 'Typing enthusiast and tech aficionado.',
        avgWPM: 105.6,
        highestWPM: 125.0,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 5,
        username: 'chrisjohnson',
        bio: 'Admin by day, typist by night.',
        avgWPM: 110.8,
        highestWPM: 135.2,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 6,
        username: 'emilywhite',
        bio: 'Tech lover with a passion for high-speed typing.',
        avgWPM: 113.5,
        highestWPM: 138.9,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 7,
        username: 'davidbrown',
        bio: 'Challenge seeker in typing and problem-solving.',
        avgWPM: 104.0,
        highestWPM: 126.5,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 8,
        username: 'sarahsmith',
        bio: 'Typing fan and quick learner.',
        avgWPM: 107.4,
        highestWPM: 129.3,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 9,
        username: 'brucelee',
        bio: 'Admin with a passion for precision and speed.',
        avgWPM: 111.3,
        highestWPM: 137.7,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 10,
        username: 'rachelgreen',
        bio: 'Speed typing enthusiast.',
        avgWPM: 99.2,
        highestWPM: 119.5,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 11,
        username: 'oliverqueen',
        bio: 'Archer and typing speedster.',
        avgWPM: 108.7,
        highestWPM: 132.4,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 12,
        username: 'peterparker',
        bio: 'Hero and typing enthusiast.',
        avgWPM: 102.9,
        highestWPM: 127.8,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 13,
        username: 'tonystark',
        bio: 'Admin and inventor with fast fingers.',
        avgWPM: 116.2,
        highestWPM: 139.1,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 14,
        username: 'clarkkent',
        bio: 'Mild-mannered reporter and typist.',
        avgWPM: 109.6,
        highestWPM: 131.0,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 15,
        username: 'dianaprince',
        bio: 'Amazonian typist and admin.',
        avgWPM: 112.1,
        highestWPM: 136.0,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 16,
        username: 'steverogers',
        bio: 'Soldier with a passion for speed typing.',
        avgWPM: 97.8,
        highestWPM: 118.7,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 17,
        username: 'natasharomanoff',
        bio: 'Admin and stealthy typist.',
        avgWPM: 114.5,
        highestWPM: 137.8,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 18,
        username: 'brucewayne',
        bio: 'Strategist and typist.',
        avgWPM: 101.2,
        highestWPM: 123.4,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 19,
        username: 'loganhowlett',
        bio: 'Typing challenger with quick reflexes.',
        avgWPM: 106.0,
        highestWPM: 129.1,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 20,
        username: 'arthurcurry',
        bio: 'King of the sea and typing speed.',
        avgWPM: 105.4,
        highestWPM: 126.8,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 21,
        username: 'barryallen',
        bio: 'Fastest typist alive.',
        avgWPM: 130.5,
        highestWPM: 150.0,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 22,
        username: 'haljordan',
        bio: 'Green Lantern and speed typist.',
        avgWPM: 108.4,
        highestWPM: 132.5,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 23,
        username: 'clintbarton',
        bio: 'Sharp shooter and typist.',
        avgWPM: 103.6,
        highestWPM: 124.9,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 24,
        username: 'wadesmith',
        bio: 'Typing expert with a sense of humor.',
        avgWPM: 110.0,
        highestWPM: 135.0,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 25,
        username: 'charlesxavier',
        bio: 'Admin and telepathic typist.',
        avgWPM: 117.2,
        highestWPM: 140.8,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 26,
        username: 'jeangrey',
        bio: 'Typing speed and psychic powers combined.',
        avgWPM: 108.9,
        highestWPM: 132.1,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 27,
        username: 'scottsummers',
        bio: 'Laser-focused on typing accuracy.',
        avgWPM: 106.7,
        highestWPM: 127.5,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 28,
        username: 'ororomunroe',
        bio: 'Weather control and typing master.',
        avgWPM: 111.1,
        highestWPM: 136.3,
        startDate: startDate,
        role: 'admin',
    }),
    new Profile({
        id: 29,
        username: 'remylebeau',
        bio: 'Card sharp and fast typist.',
        avgWPM: 104.8,
        highestWPM: 128.3,
        startDate: startDate,
        role: 'player',
    }),
    new Profile({
        id: 30,
        username: 'bobbydrake',
        bio: 'Cool typist with impressive speed.',
        avgWPM: 107.3,
        highestWPM: 130.9,
        startDate: startDate,
        role: 'player',
    }),
];

const getAllProfiles = (): Profile[] => {
    return profiles;
};

const getProfileById = (id: number): Profile | undefined => {
    return profiles.find((profile) => profile.getId() === id);
};

export default {
    getAllProfiles,
    getProfileById,
};
