import { User } from '../model/user';

const users = [
    new User({
        id: 1,
        username: 'johndoe',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@ucll.be',
        password: 'johnd123',
        role: 'player',
    }),
    new User({
        id: 2,
        username: 'janedoe',
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane.doe@ucll.be',
        password: 'janed123',
        role: 'player',
    }),
    new User({
        id: 3,
        username: 'michaelking',
        firstName: 'Michael',
        lastName: 'King',
        email: 'michael.king@ucll.be',
        password: 'michael123',
        role: 'player',
    }),
    new User({
        id: 4,
        username: 'lindawalker',
        firstName: 'Linda',
        lastName: 'Walker',
        email: 'linda.walker@ucll.be',
        password: 'linda123',
        role: 'player',
    }),
    new User({
        id: 5,
        username: 'chrisjohnson',
        firstName: 'Chris',
        lastName: 'Johnson',
        email: 'chris.johnson@ucll.be',
        password: 'chrisj123',
        role: 'admin',
    }),
    new User({
        id: 6,
        username: 'emilywhite',
        firstName: 'Emily',
        lastName: 'White',
        email: 'emily.white@ucll.be',
        password: 'emilyw123',
        role: 'admin',
    }),
    new User({
        id: 7,
        username: 'davidbrown',
        firstName: 'David',
        lastName: 'Brown',
        email: 'david.brown@ucll.be',
        password: 'davidb123',
        role: 'player',
    }),
    new User({
        id: 8,
        username: 'sarahsmith',
        firstName: 'Sarah',
        lastName: 'Smith',
        email: 'sarah.smith@ucll.be',
        password: 'sarahs123',
        role: 'player',
    }),
    new User({
        id: 9,
        username: 'brucelee',
        firstName: 'Bruce',
        lastName: 'Lee',
        email: 'bruce.lee@ucll.be',
        password: 'brucel123',
        role: 'admin',
    }),
    new User({
        id: 10,
        username: 'rachelgreen',
        firstName: 'Rachel',
        lastName: 'Green',
        email: 'rachel.green@ucll.be',
        password: 'rachelg123',
        role: 'player',
    }),
    new User({
        id: 11,
        username: 'oliverqueen',
        firstName: 'Oliver',
        lastName: 'Queen',
        email: 'oliver.queen@ucll.be',
        password: 'oliverq123',
        role: 'player',
    }),
    new User({
        id: 12,
        username: 'peterparker',
        firstName: 'Peter',
        lastName: 'Parker',
        email: 'peter.parker@ucll.be',
        password: 'peterp123',
        role: 'player',
    }),
    new User({
        id: 13,
        username: 'tonystark',
        firstName: 'Tony',
        lastName: 'Stark',
        email: 'tony.stark@ucll.be',
        password: 'tonys123',
        role: 'admin',
    }),
    new User({
        id: 14,
        username: 'clarkkent',
        firstName: 'Clark',
        lastName: 'Kent',
        email: 'clark.kent@ucll.be',
        password: 'clarkk123',
        role: 'player',
    }),
    new User({
        id: 15,
        username: 'dianaprince',
        firstName: 'Diana',
        lastName: 'Prince',
        email: 'diana.prince@ucll.be',
        password: 'dianap123',
        role: 'admin',
    }),
    new User({
        id: 16,
        username: 'steverogers',
        firstName: 'Steve',
        lastName: 'Rogers',
        email: 'steve.rogers@ucll.be',
        password: 'stever123',
        role: 'player',
    }),
    new User({
        id: 17,
        username: 'natasharomanoff',
        firstName: 'Natasha',
        lastName: 'Romanoff',
        email: 'natasha.romanoff@ucll.be',
        password: 'natashar123',
        role: 'admin',
    }),
    new User({
        id: 18,
        username: 'brucewayne',
        firstName: 'Bruce',
        lastName: 'Wayne',
        email: 'bruce.wayne@ucll.be',
        password: 'brucew123',
        role: 'player',
    }),
    new User({
        id: 19,
        username: 'loganhowlett',
        firstName: 'Logan',
        lastName: 'Howlett',
        email: 'logan.howlett@ucll.be',
        password: 'loganh123',
        role: 'player',
    }),
    new User({
        id: 20,
        username: 'arthurcurry',
        firstName: 'Arthur',
        lastName: 'Curry',
        email: 'arthur.curry@ucll.be',
        password: 'arthurc123',
        role: 'player',
    }),
    new User({
        id: 21,
        username: 'barryallen',
        firstName: 'Barry',
        lastName: 'Allen',
        email: 'barry.allen@ucll.be',
        password: 'barrya123',
        role: 'player',
    }),
    new User({
        id: 22,
        username: 'haljordan',
        firstName: 'Hal',
        lastName: 'Jordan',
        email: 'hal.jordan@ucll.be',
        password: 'halj123',
        role: 'player',
    }),
    new User({
        id: 23,
        username: 'clintbarton',
        firstName: 'Clint',
        lastName: 'Barton',
        email: 'clint.barton@ucll.be',
        password: 'clintb123',
        role: 'player',
    }),
    new User({
        id: 24,
        username: 'wadesmith',
        firstName: 'Wade',
        lastName: 'Smith',
        email: 'wade.smith@ucll.be',
        password: 'wades123',
        role: 'player',
    }),
    new User({
        id: 25,
        username: 'charlesxavier',
        firstName: 'Charles',
        lastName: 'Xavier',
        email: 'charles.xavier@ucll.be',
        password: 'charlesx123',
        role: 'admin',
    }),
    new User({
        id: 26,
        username: 'jeangrey',
        firstName: 'Jean',
        lastName: 'Grey',
        email: 'jean.grey@ucll.be',
        password: 'jeang123',
        role: 'player',
    }),
    new User({
        id: 27,
        username: 'scottsummers',
        firstName: 'Scott',
        lastName: 'Summers',
        email: 'scott.summers@ucll.be',
        password: 'scotts123',
        role: 'player',
    }),
    new User({
        id: 28,
        username: 'ororomunroe',
        firstName: 'Ororo',
        lastName: 'Munroe',
        email: 'ororo.munroe@ucll.be',
        password: 'ororom123',
        role: 'admin',
    }),
    new User({
        id: 29,
        username: 'remylebeau',
        firstName: 'Remy',
        lastName: 'LeBeau',
        email: 'remy.lebeau@ucll.be',
        password: 'remyl123',
        role: 'player',
    }),
    new User({
        id: 30,
        username: 'bobbydrake',
        firstName: 'Bobby',
        lastName: 'Drake',
        email: 'bobby.drake@ucll.be',
        password: 'bobbyd123',
        role: 'player',
    }),
];

const getAllUsers = (): User[] => {
    return users;
};

const getUserById = (id: number): User | undefined => {
    return users.find((user) => user.getId() === id);
};

export default {
    getAllUsers,
    getUserById,
};
